### ISSUE TITLE
Errors not defined?

### ISSUE THREAD

**Issue by CountCulture** [scraperwiki/scraperwiki-ruby#15]
Is it me, or are the errors (e.g. NoSuchTableSqliteException) not defined?

**Comment by pwaller** [comment]
I don't find `NoSuchTableSqliteException` anywhere in this project. Can you elaborate? If you are still interested in resolving this issue reply and I will reopen it.

**Comment by CountCulture** [comment]
For clarification (for future visitors) this bug related to old version. The code has been now abstracted to the sqlite_magic gem

**Comment by pwaller** [comment]
:+1:
