### ISSUE TITLE
Classes not typecast

### ISSUE THREAD

**Issue by henare** [scraperwiki/scraperwiki-ruby#20]
I used to have a scraper where I passed an error class (`OpenURI::HTTPError`) to be saved in the DB by `save_sqlite`.

ScraperWiki would to typecast it to a string but scraperwiki-ruby doesn't do this.

**Comment by henare** [comment]
I fixed a similar typecasting thing in https://github.com/henare/scraperwiki-ruby/commit/c5f5f6dba4ddff2ba604f49ba1adc0d9c142e6e9 which is available in #18

**Comment by pwaller** [comment]
Please rebase and reopen #18 if you want this addressed, thanks!
